[KED-3063] Scaffolding Kedro Website
kedro-org/kedro-website pull request #1
Opened 2022-02-04 12:18 UTC by rashidakanchwala

2022-02-04 13:43 UTC, studioswong requested changes
Thanks for setting this up.

Before we go deeper in the review, one main thing to confirm with the team - are we using typescript for the website development? Asking this as I don't see any mention of using typescript for this ticket or for the site development. 

 Not that I am against it at all, but developing on normal JS/JSX as compared to typescript has implications on initial velocity for future development of the site as the team would need to pick up new syntax and get used to new practices for typescript. ( typescript has a lot of immediate benefits that is definitely very suited to the Kedro-viz project, but not sure if it is exactly necessary for the development on the static site where we can put the efforts to focus on building beautiful FE elements rather than on types.)

2022-02-04 13:43 UTC, studioswong commented on jest.config.js
> +  // if using TypeScript with a baseUrl set to the root directory then you need the below for alias' to work
let's take these template comments out

2022-02-04 13:43 UTC, studioswong commented on jest.config.js
> +// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
same for this comment

2022-02-04 14:32 UTC, tynandebold commented
> Thanks for setting this up.
> 
> Before we go deeper in the review, one main thing to confirm with the team - are we using typescript for the website development? Asking this as I don't see any mention of using typescript for this ticket or for the site development.
> 
> Not that I am against it at all, but developing on normal JS/JSX as compared to typescript has implications on initial velocity for future development of the site as the team would need to pick up new syntax and get used to new practices for typescript. ( typescript has a lot of immediate benefits that is definitely very suited to the Kedro-viz project, but not sure if it is exactly necessary for the development on the static site where we can put the efforts to focus on building beautiful FE elements rather than on types.)

Yeah it wasn't in the ticket and was discussed more offline, but TypeScript seems like a nice choice here for a few reasons, the big one being that this site will be so simple. In this case, it won't be too big an ask to learn this new syntax because the components we need to make are straightforward. Further, if one is coming from a strongly-typed language like Python, it might even be easier to pick up TS over JS. And lastly, this begins to align the JS we write on the Kedro team with the wider QB frontend code, which is mainly all TS, as far as I understand.

2022-02-04 14:32 UTC, tynandebold commented on package.json
> +  }
Definitely.

2022-02-04 14:56 UTC, studioswong commented
sure, I'm all up for typescript generally, thanks for clarifying about the offline discussion - moving forward, please do update the team on these core decisions (esp. about the choice of language) on the channel or the Jira ticket for clarity and alignment.

I agree that using the kedro website as a playground for the team to pick up typescript is generally a good idea ( not sure about the python comparison as this is essentially a FE codebase and the concepts/syntax/use cases are still very different.) 
It makes sense to align with wider QB FE codebase too - let's go for it then.

2022-02-07 10:08 UTC, tynandebold approved these changes
Amazing work!

2022-02-07 15:08 UTC, studioswong commented on pages/_app.tsx
> +function MyApp({ Component, pageProps }: AppProps) {
Let's call this `KedroWebsite`  rather than the placeholder `MyApp`

2022-02-07 15:36 UTC, tynandebold commented on package.json
> +      "pre-commit": "lint-staged"
why twice? won't it be in the same state between commit and push?

2022-02-07 15:39 UTC, studioswong commented on package.json
> +      "pre-commit": "lint-staged"
I'm referring to add the hook we have set up in the kedro-viz repo, `"pre-push": "npm run test" `

2022-02-07 15:45 UTC, tynandebold commented on package.json
> +      "pre-commit": "lint-staged"
oh yes definitely good call

2022-02-07 18:54 UTC, merged