Feature/our community 135
kedro-org/kedro-website pull request #136
Opened 2023-05-16 15:53 UTC by ravi-kumar-pilla

## Description

Resolves #135
 
## Development notes

Changed Our community section from displaying as grid to an infinite carousel using the [design link](https://www.figma.com/file/fJLMAWpBfh75loDtclpdXR/Kedro-Website?type=design&node-id=1622-5870&t=DQ1Fq7rg4ClDGwAH-0).

## QA notes

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Added tests to cover my changes, where applicable

2023-05-16 16:13 UTC, tynandebold commented
@astrojuanlu the deploy preview is coming online now.

2023-05-16 16:35 UTC, tynandebold requested changes
Wow, your first PR already! Amazing job!

I've left some comments, a couple around some coding styles we like to try and stick to on the team.

One thing I'm noticing when looking at the animation in Chrome is that it's a little laggy/jumpy. Are you seeing the same? Maybe there's a way we can smooth that out with a browser prefix. It's very smooth on Safari.

Another thing: we'll need to do something different with the layout on mobile. For now, I think you can stack the `Our community` text above the animating logos and center align everything, following the convention from the other components.

Lastly, try and use hyphens in your branch names and be a little more descriptive with your PR naming. We don't need to micim what we use for branch names. I've updated it so you can see what I mean as an example.

Overall, amazing work! Onwards and upwards!

2023-05-16 16:35 UTC, tynandebold commented on modules/index/companies-using-kedro/companies-using-kedro.module.scss
> +    @include breakpoint(small) {
Try and have a blank line before `@` rules.

```suggestion
    padding-right: 2em;
    
    @include breakpoint(small) {
```

2023-05-16 16:35 UTC, tynandebold commented on modules/index/companies-using-kedro/companies-using-kedro.module.scss
> +  position: relative;
I like to try and sort things (CSS styles, React props) alphabetically so it's easier for a reader to find what they're looking for.

```suggestion
  display: flex;
  overflow: hidden;
  position: relative;
  width: 100%;
```

2023-05-16 16:35 UTC, tynandebold commented on modules/index/companies-using-kedro/companies-using-kedro.tsx
> +          </div>
This code is repeated above. Is that by design? If so, why?

2023-05-16 16:35 UTC, tynandebold commented on package-lock.json
Can you try to remove this from your PR? I'm not sure why there are so many changes in this file. Which version of Node are you using when you run `npm install`? Try and use `v16`.

2023-05-17 20:41 UTC, tynandebold approved these changes
Looks good!

One last thing you need to change is to add a `max-width` to the element with a class of `.outer`. Looking at the designs, the max width of the content shouldn't be greater that `1280px`. Is that right @Mackay031.

Happy to approve now and have you add that in before merging.

2023-05-18 07:29 UTC, Huongg approved these changes
Looking good to me too @ravi-kumar-pilla, amazing job 😄

2023-05-22 10:05 UTC, merged