Companies - WIP
kedro-org/kedro-website pull request #23
Opened 2022-03-15 13:02 UTC by rashidakanchwala

2022-03-25 11:05 UTC, tynandebold requested changes
Amazing stuff. Definitely my favorite component on the page :)

I've left some comments. None of them are huge. Let me know what you think.

2022-03-25 11:05 UTC, tynandebold commented on components/companies/companies.tsx
> +                <li>Telkomsel</li>
I'd suggest we create an array of a list of companies and then map through them. It'll be a little cleaner and easier to maintain. 

And then if you need a 'buffer' company above and below, you can add those values afterwards with `push()` and `unshift()`.

2022-03-25 17:04 UTC, tynandebold approved these changes
Looking great to me!

Just a couple of small considerations for you look at, all at your discretion.

2022-03-25 17:04 UTC, tynandebold commented on components/companies-using-kedro/content.tsx
> +export const content = [
Love that you moved this to an array. Since it's only this, you could put it in the `companies-using-kedro` file if you wanted to, but your call!

2022-03-29 15:04 UTC, studioswong approved these changes
Thanks for the great work, animation is looking good 💯 

Happy to approve this, with the following minor comments / observations ( which I'll leave it up to you to decide -

 the animation seems to be bleeding towards the edge on the ipad mini breakpoint - might be worth adding a border for this ( I've also encountered the same problem with mobile on ipad mini breakpoints for the use cases section as well, perhaps you could also reference the css settings there): 

<img width="668" alt="image" src="https://user-images.githubusercontent.com/27775658/160637349-953489ad-40f1-46fe-ad3c-0e765a8e42bf.png">

Thank you 😄

2022-03-30 11:01 UTC, merged